package httptape

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"strings"
	"time"
)

// BuildTLSConfig constructs a *tls.Config from optional PEM file paths and an
// insecure flag. All parameters are optional; an all-zero call returns nil
// (meaning "use Go defaults").
//
// Parameters:
//   - certFile, keyFile: PEM-encoded client certificate and private key for
//     mTLS. Both must be provided together; providing one without the other
//     returns an error.
//   - caFile: PEM-encoded CA certificate(s) to use as the root CA pool for
//     verifying the upstream server. When empty, the system root CAs are used.
//   - insecure: when true, sets InsecureSkipVerify on the returned config.
//
// Returns nil, nil when all parameters are zero-valued (no custom TLS needed).
func BuildTLSConfig(certFile, keyFile, caFile string, insecure bool) (*tls.Config, error) {
	// Validate cert/key pairing: both or neither.
	if certFile != "" && keyFile == "" {
		return nil, fmt.Errorf("httptape: --tls-cert requires --tls-key")
	}
	if keyFile != "" && certFile == "" {
		return nil, fmt.Errorf("httptape: --tls-key requires --tls-cert")
	}

	// If nothing is configured, return nil (use Go defaults).
	if certFile == "" && keyFile == "" && caFile == "" && !insecure {
		return nil, nil
	}

	cfg := &tls.Config{}

	// Load client certificate for mTLS.
	if certFile != "" && keyFile != "" {
		cert, err := tls.LoadX509KeyPair(certFile, keyFile)
		if err != nil {
			return nil, fmt.Errorf("httptape: load client certificate: %w", err)
		}
		cfg.Certificates = []tls.Certificate{cert}
	}

	// Load custom CA.
	if caFile != "" {
		caPEM, err := os.ReadFile(caFile)
		if err != nil {
			return nil, fmt.Errorf("httptape: read CA file: %w", err)
		}
		pool := x509.NewCertPool()
		if !pool.AppendCertsFromPEM(caPEM) {
			return nil, fmt.Errorf("httptape: no valid certificates found in CA file %q", caFile)
		}
		cfg.RootCAs = pool
	}

	// Insecure skip verify.
	if insecure {
		cfg.InsecureSkipVerify = true
	}

	return cfg, nil
}

// SelfSignedCert holds a self-signed TLS certificate generated by
// GenerateSelfSignedCert. The certificate and key material are kept in
// memory only and are never written to disk.
type SelfSignedCert struct {
	// TLSCertificate is the parsed certificate ready for use in tls.Config.
	TLSCertificate tls.Certificate

	// CertPEM is the PEM-encoded certificate bytes. Useful for configuring
	// clients that need to trust this certificate (e.g., via tls.Config.RootCAs).
	CertPEM []byte

	// Fingerprint is the SHA-256 fingerprint of the DER-encoded certificate,
	// formatted as colon-separated uppercase hex (e.g., "AB:CD:EF:...").
	Fingerprint string
}

// GenerateSelfSignedCert produces an ECDSA P-256 self-signed certificate
// for the given hosts (DNS names and/or IP addresses).
// If hosts is empty, the certificate covers "localhost", "127.0.0.1", and "::1".
// Validity: 24 hours from now, with NotBefore set 1 hour in the past for clock skew.
//
// For local development and tests only. Never trust self-signed certificates
// in production. Clients trusting the returned cert should do so programmatically
// via tls.Config.RootCAs in test code only.
func GenerateSelfSignedCert(hosts ...string) (*SelfSignedCert, error) {
	if len(hosts) == 0 {
		hosts = []string{"localhost", "127.0.0.1", "::1"}
	}

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("httptape: generate ECDSA key: %w", err)
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return nil, fmt.Errorf("httptape: generate serial number: %w", err)
	}

	now := time.Now()
	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject:      pkix.Name{CommonName: "httptape self-signed"},
		NotBefore:    now.Add(-1 * time.Hour),
		NotAfter:     now.Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}

	for _, h := range hosts {
		if ip := net.ParseIP(h); ip != nil {
			template.IPAddresses = append(template.IPAddresses, ip)
		} else {
			template.DNSNames = append(template.DNSNames, h)
		}
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, fmt.Errorf("httptape: create self-signed certificate: %w", err)
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("httptape: marshal ECDSA key: %w", err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return nil, fmt.Errorf("httptape: parse generated key pair: %w", err)
	}

	fingerprint := sha256.Sum256(certDER)
	var parts []string
	for _, b := range fingerprint {
		parts = append(parts, fmt.Sprintf("%02X", b))
	}

	return &SelfSignedCert{
		TLSCertificate: tlsCert,
		CertPEM:        certPEM,
		Fingerprint:    strings.Join(parts, ":"),
	}, nil
}
